backend:
  name: github
    repo: jenshector/ignicon-hemsida
      branch: main

      media_folder: "bilder"
      public_folder: "/bilder"

      locale: 'sv'

      collections:
        - name: "inlagg"
            label: "Blogginlagg"
                folder: "_posts"
                    create: true
                        slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
                            fields:
                                  - { label: "Rubrik", name: "title", widget: "string" }
                                        - { label: "Publiceringsdatum", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
                                              - label: "Kategori"
                                                      name: "category"
                                                              widget: "select"
                                                                      options:
                                                                                - { label: "Ledarskap", value: "Ledarskap" }
                                                                                          - { label: "Grupputveckling", value: "Grupputveckling" }
                                                                                                    - { label: "Ledningsgrupp", value: "Ledningsgrupp" }
                                                                                                              - { label: "Coaching", value: "Coaching" }
                                                                                                                        - { label: "Organisation", value: "Organisation" }
                                                                                                                              - { label: "Kort beskrivning", name: "excerpt", widget: "text" }
                                                                                                                                    - { label: "Lasttid", name: "readtime", widget: "string", default: "4 min lasning" }
                                                                                                                                          - { label: "Innehall", name: "body", widget: "markdown" }
                                                                                                                                                - { label: "Utvalt inlagg?", name: "featured", widget: "boolean", default: false, required: false }
